apiVersion: triggers.tekton.dev/v1beta1
kind: ClusterTriggerBinding
metadata:
  name: gitlab-push-hack
spec:
  params:
  - name: git-revision
    value: $(body.checkout_sha)
  - name: git-commit-message
    value: $(body.commits[0].message)
  - name: git-repo-url
    value: $(body.repository.git_http_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: pusher-name
    value: $(body.user_name)
  - name: git-repo-event-target-ref
    value: $(extensions.branch_name)
  - name: pipelinerun-name
    value: $(extensions.pipelinerun_name)

