apiVersion: route.openshift.io/v1
kind: Route
spec:
  host: rekor-server-sigstore.apps.cluster-fd74.fd74.sandbox195.opentlc.com
  port:
    targetPort: 3000-tcp
  to:
    kind: Service
    name: rekor-server
    weight: 100
  wildcardPolicy: None
metadata:
  name: rekor-server
