apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: manual-typical-
spec:
  params:
  - name: verbose
    value: "true"
  - name: appRepoUrl
    value: http://gitea.devsecops.svc.cluster.local:3000/platform/reference-quarkus-mvn.git
  - name: appRepoRef
    value: main
  - name: appCloneSSLVerify
    value: "false"
  - name: stepRunnerConfigDir
    value: /opt/platform-config/ /opt/platform-config-secrets/ cicd/ploigos-software-factory-operator/ploigos-step-runner-config/
  - name: pgpKeysSecretName
    value: ploigos-gpg-key
  - name: envNameDev
    value: DEV
  - name: envNameTest
    value: TEST
  - name: envNameProd
    value: PROD
  - name: ciOnlyGitRefPatterns
    value: ^$
  - name: devGitRefPatterns
    value: ^feature/.+$|^PR-.+$
  - name: releaseGitRefPatterns
    value: ^main$
  - name: stepRunnerPackageName
    value: ploigos-step-runner
  - name: stepRunnerUpdateLibrary
    value: "false"
  - name: stepRunnerLibIndexUrl
    value: https://pypi.org/simple/
  - name: stepRunnerLibExtraIndexUrl
    value: https://pypi.org/simple/
  - name: stepRunnerLibVersion
    value: v0.16.0
  - name: stepRunnerLibSourceUrl
    value: https://github.com/ploigos/ploigos-step-runner.git
  - name: workflowWorkerImageDefault
    value: quay.io/ploigos/ploigos-tool-maven:latest
  - name: workflowWorkerImageSourceClone
    value: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.12.1
  - name: workflowWorkerImageUnitTest
    value: quay.io/ploigos/ploigos-tool-maven:latest
  - name: workflowWorkerImagePackage
    value: quay.io/ploigos/ploigos-tool-maven:latest
  - name: workflowWorkerImageStaticCodeAnalysis
    value: quay.io/ploigos/ploigos-tool-sonar:latest
  - name: workflowWorkerImagePushArtifacts
    value: quay.io/ploigos/ploigos-tool-maven:latest
  - name: workflowWorkerImageContainerOperations
    value: quay.io/ploigos/ploigos-tool-containers:latest
  - name: workflowWorkerImageContainerImageStaticComplianceScan
    value: quay.io/ploigos/ploigos-tool-openscap:latest
  - name: workflowWorkerImageContainerImageStaticVulnerabilityScan
    value: quay.io/ploigos/ploigos-tool-openscap:latest
  - name: workflowWorkerImageDeploy
    value: quay.io/ploigos/ploigos-tool-argocd:latest
  - name: workflowWorkerImageValidateEnvironmentConfiguraiton
    value: quay.io/ploigos/ploigos-tool-config-lint:latest
  - name: workflowWorkerImageUAT
    value: quay.io/ploigos/ploigos-tool-maven:latest
  pipelineRef:
    name: ref-quarkus-mvn-fruit
  serviceAccountName: ploigos-workflow-ref-quarkus-mvn-fruit
  timeout: 1h0m0s
  workspaces:
  - name: home
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      status: {}
  - name: app
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - configMap:
      name: ploigos-platform-config-mvn
    name: ploigos-platform-config
  - name: ploigos-platform-config-secrets
    secret:
      secretName: ploigos-platform-config-secrets-mvn

